# Generated by Django 3.1.5 on 2021-01-11 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumer_name', models.CharField(max_length=30)),
                ('consumer_no', models.CharField(max_length=20)),
                ('phone_no', models.CharField(max_length=10)),
                ('date', models.DateField()),
            ],
        ),
    ]
