# Generated by Django 3.1.7 on 2021-03-06 07:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(default='pending', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='time',
            field=models.TimeField(default=datetime.datetime(2021, 3, 6, 7, 59, 44, 154753, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
